In [6]:
import numpy as np 
  
  
tab1 = np.array([0,1,2]) 
tab2 = np.array([2,1,0]) 
  
print(tab1) 
  
print(tab2) 
  
print("\nLa matrice de covariance est:\n", 
      np.cov(array1, array2)) 

[0 1 2]
[2 1 0]

La matrice de covariance est:
 [[ 1. -1.]
 [-1.  1.]]
